### ISSUE TITLE
GitHub Actions to deploy Azure resources and application code failed

### ISSUE THREAD

**Issue by puicchan** [Azure-Samples/app-templates-staticwebapp-cosmosdb#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

1. Fork the repo
2. Follow steps in readme to create SP and store secret in GH
3. Updated build-deploy.yaml. DEPLOYMENT_NAME: "csu830" and DEPLOYMENT_REGION: "eastus"
4. Ran the workflow "Build and Deploy Application" in GH.

### Any log messages given by the failure

The job Deploy Azure Resources failed with message:
"Error: The process '/usr/bin/pwsh' failed with exit code 1"

Error in detailed log:
New-AzDeployment: /home/runner/work/_temp/67100fa5-f623-4939-87a2-277c91cbde7c.ps1:6
Line |
   6 |  $res = New-AzDeployment -Name $deploymentName -TemplateFile "infra/ma …
     |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 17:15:55 - The deployment 'csu830-eastus' failed with
     | error(s). Showing 1 out of 1 error(s). Status Message: The
     | template deployment 'csu830-rg-function' is not valid
     | according to the validation procedure. The tracking id is
     | 'cbbde072-b8b9-484b-af51-07f0fd54c622'. See inner errors for
     | details. (Code: InvalidTemplateDeployment)  - Object
     | reference not set to an instance of an object. (Code:)  
     | CorrelationId: 2[70](https://github.com/puicchan/app-templates-staticwebapp-cosmosdb/runs/8119131841?check_suite_focus=true#step:4:71)0a3b6-7586-4fbd-bade-2f5a1b022c09

### Expected/desired behavior
>

Able to provision Azure resources as well as deploy the application.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by nielsams** [comment]
Hi @puicchan ,
I'm looking into your deployment issue but am unable to repro it. Things work fine if I use your settings (with csu820 instead). 
1) Can you confirm your service principal has contributor permissions on the subscription?
2) Can you look in the portal to see if the resource group was created and if so, have a look under the deployment tab of the RG to see if there are any more errors visible for the deployment called 'csu831-rg-function'?

**Comment by puicchan** [comment]
Yes, SP has contributor permission. I just reran. Updated region to southcentralus and everything went through this time. May be previous error was a transient error.
